- {title: 'Full Member, Acceleration Consortium', description: 'University of Toronto (2021 – present)'}
- {title: 'Editorial Board Member', description: 'RSC Digital Discovery (2021 – present)'}
- {title: 'Editorial Advisory Board', description: 'ACS Polymers Au (2021 – present)'}
- {title: 'Editorial Advisory Board', description: 'ACS Applied Polymer Materials (2021 – present)'}
- {title: 'Chair, 2024 ACS Colloid and Surface Science Symposium', description: 'University of Washington (2021 – 2024)'}
- {title: 'Chair, Beamtime Allocation Committee', description: 'NIST Center for Neutron Research (2015 – 2018)'}
